@startuml

class Airport <<Entity>> {
  - airportId : String
  - name : String
  - code : String
  - location : Location
  + updateLocation()
}

class Route <<Entity>> {
  - routeId : String
  - origin : Airport
  - destination : Airport
  - distance : Distance
  - requiredRange : double
  - requiredCapacity : int
  - monthlyAverageFlights : double
  + updateMonthlyAverageFlights()
}

class Location <<ValueObject>> {
  - latitude : double
  - longitude : double
}

class Distance <<ValueObject>> {
  - value : double
}

class Flight <<Entity>> {
  - flightId : String
  - schedule : FlightSchedule
  - aircraftId : String
  - routeId : String
  + checkRequirements()
}

class FlightSchedule <<ValueObject>> {
  - departureTime : LocalDateTime
  - arrivalTime : LocalDateTime
  + getDuration()
}

Flight "1" --> "1" Route : follows
Flight "1" --> "1" Aircraft : utilizes
Flight "1" *-- "1" FlightSchedule

Airport "1" *-- "1" Location
Route "1" *-- "1" Distance

Route "1" --> "1" Airport : origin
Route "1" --> "1" Airport : destination

@enduml